### ISSUE TITLE
Static extension problem with Thenable?

### ISSUE THREAD

**Issue by cambiata** [basro/hx-jsasync#4] opened 2021-01-22 11:47 UTC
Using .jsawait() as a static extension doesn't work for me - the compiler complains with
`src/Main.hx:8: characters 24-31 : JSASync: js.lib.Promise<String> has no field jsawait`

I guess it's because the promise is typed as `js.lib.Promise.Thenable`, not as `js.lib.Promise` (as in the deprecated .await() function, wich works!) When replacing

`public static extern inline function jsawait<T>(promise:js.lib.Promise.Thenable<T>):T`

with

`public static extern inline function jsawait<T>(promise:js.lib.Promise<T>):T`

it works as expected.

**Comment by basro** [comment] 2021-01-22 12:03
I'm unable to reproduce this problem.

Which version of Haxe are you using? Could you provide some code that reproduces it?

**Comment by cambiata** [comment] 2021-01-22 13:24
Seems to be a 4.2 problem, works fine with 4.1.5...
![jsasync](https://user-images.githubusercontent.com/217074/105496206-7798a980-5cbd-11eb-825c-71434fe1f36c.png)

**Comment by basro** [comment] 2021-01-22 13:51
Interesting, must be a relatively recent 4.2 problem, I had tested with a nightly version a while ago and it worked fine too.

I'll try to investigate this later today or during the weekend.

**Comment by cambiata** [comment] 2021-01-22 15:07
No problem for me - easily "solved" by removing `.Thenable`. 
Using jsasync for the first time in a "real" project - really saves a lot of time when it comes to deal with async-sprinkled js code.. Thanks!

**Comment by basro** [comment] 2021-01-24 14:57
I'm very glad that it's useful to you!

I've tried with the latest Haxe nightly (8c0d30b) and I still can't reproduce this problem with Thenable.

Which build are you are using? Could you upgrade to latest to see if it still happens with it?

**Comment by basro** [comment] 2021-03-05 14:44
I'm closing this issue since I was unable to reproduce it, it would be nice to know if it's working fine for you with the now released (non nightly) haxe 4.2.

**Closed as completed by basro** 2021-03-05 14:44 UTC
